### ISSUE TITLE
How to use ejs in IE browser with async: true ?

### ISSUE THREAD

**Issue by usb248** [mde/ejs#504] opened 2020-03-28 00:21 UTC
Actually, i get this error which fails all my APP.
`'This environment does not support async/await'`

How to use async version in IE ? Any support for IE ?

This way is exactly the same behavior ?
```
renderEjs(){
	  	    	return new Promise((resolve, reject) => {
	  	    		const compiled  = ejs.render(
	  	    			template,
	  	    			data,
	  	    			{ client: true }
	  	    		)
	  	    		resolve(compiled)
	  	    	})
	  	    }
```

**Comment by mde** [comment] 2020-03-28 03:32
That means there is no native support for Promises in that browser. There may be some polyfills available to try, but this is not an EJS issue. I am closing this. Feel free to reopen if you have something EJS-specific that we can help you with.

**Closed by mde** 2020-03-28 03:32 UTC

**Comment by usb248** [comment] 2020-03-28 09:18
Okey I ask my question differently.
I know that IE sucks. I known too what means this message thanks but you don't answer my question.

**This is the same OR not ?**
```
renderEjs(){
	  	    	return new Promise((resolve, reject) => {
	  	    		const compiled  = ejs.render(
	  	    			template,
	  	    			data,
	  	    			{ client: true }
	  	    		)
	  	    		resolve(compiled)
	  	    	})
	  	    }
```
My entire app is transpiled to ES5 with promise polyfill. Why EJS doesn't try the most famous `Promise` syntax rather than throw an Error :unamused: ?

**Comment by mde** [comment] 2020-03-29 17:37
I have been writing JavaScript since the late 90s, and Promises/Deferreds/Futures have been around in some form in JS programming since MochiKit or Dojo, in the mid-2000s. They have always been a complicated and frustrating API to interact with, particularly with respect to handling errors (or not handling them, in many cases). To make matter worse, these various implementations did not behave consistently. Async/await however, is a genuinely useful addition to the language, making async code much more readable, at the cost of some annoying subtleties caused by making async operations appear to be synchronous, and also sometimes requiring an interaction with, and understanding of, their underlying Promisey implementation. In short: I have zero interest in wrangling Promises, except in the service of providing a nice async/await API — particularly in service of supporting a browser which is effectively EOL'd by its vendor (yes, technically IE 11 will continue to receive security updates as long as Windows 10 is supports, but Edge is broadly available, and MS would overwhelmingly prefer you use that), and has only the tiniest fraction of market share.
