### ISSUE TITLE
Template strings

### ISSUE THREAD

**Issue by thejameskyle** [mde/ejs#99] opened 2015-07-12 01:46 UTC
```js
`${foo}`
```
```
Uncaught ReferenceError: foo is not defined
```
:cry:

**Comment by thejameskyle** [comment] 2015-07-12 02:07
Sorry, thought it had to do with arrow functions at first.

**Comment by mde** [comment] 2015-07-12 07:18
Template strings are an ES6 feature. This is part of a bigger issue of getting EJS to work with ES6. Right now ES6 support is landing in some browsers, but isn't even in the latest stable Node (v0.12). Could you close this and open an Issue for ES6 support? We might have to consider some API to allow transpiler support for use in current browsers and Node.

**Comment by herkulano** [comment] 2015-11-19 11:24
With Node v4+ Template Strings are now available by default, no transpiling.
https://nodejs.org/en/docs/es6/

**Comment by mrchief** [comment] 2015-12-03 20:27
Sad to see this still open! :sob:

**Comment by mrchief** [comment] 2015-12-03 21:02
Here's a workaround (dirty but works):

``<%- "${foo}" %>``

**Comment by mde** [comment] 2015-12-04 00:21
Actually, I'm unclear on what problem this issue is describing. Template strings work correctly with EJS in JS engines with ES6 support. A quick test in Firefox 42, at the console (EJS 2.3.4):

```javascript
typeof ejs;
"object"
ejs.render('<%= foo; %>', {foo: 'BAR'});
"BAR"
ejs.render('<%= `${foo}`; %>', {foo: 'BAR'});
"BAR"
```
If the expectation is that EJS should somehow just natively parse template strings, that's got it backward. Template strings are the JS equivalent of a HEREDOC, which work inside a programming language context.

Template strings basically allow you to embed text in JS -- EJS is for the opposite thing, letting you embed JS into text.

**Comment by mrchief** [comment] 2015-12-04 02:53
Your test is wrong. And the expectation is not for ejs to render/parse template strings. Here's a better test:

**index.js**
```
export default () => {
return `
<html>
  <head>
    <title><%= title %></title>
  </head>
  <body>$[body}</body>
</html>`
}
```

If you take this file and render it via ejs, you'll get the described error - which in this example would say - `Uncaught ReferenceError: body is not defined`

**Comment by mde** [comment] 2015-12-04 06:17
@mrchief, I've removed your comment from this issue because it contains disparaging comments about this project. There is no explicit CoC for this project (yet), but Wheaton's Law (http://knowyourmeme.com/memes/wheatons-law) is a good starting point.

You may be frustrated by this issue, and so am I now, but I expect that people who are asking for support not combine those requests with insults. Open source is a community -- multiple people put a lot of work in on this project, and are proud of the utility it provides.

You're absolutely right -- I could have attempted to get a little more clarity about what behavior is expected here before I closed the issue. I'll reopen it. I'm happy to try to provide accommodation or fixes if you'll post an explanation of your expectations using civil language.

**Comment by mrchief** [comment] 2015-12-05 02:00
I gave you a nice explanation along with a test sample. First you close the issue and now you're simply deleting other's comments.

Go ahead and delete this one too! And do tell how your actions are in accordance to the law that you so gladly point out.

**Comment by mde** [comment] 2015-12-05 03:07
I have been unfailingly polite and respectful to all commenters here. I said I was indeed wrong for closing the issue without a complete understanding of what the supposed problem is.

I deleted the comment for a very good reason, which I explained. You made insulting comments about this project. There is no universe in which deleting abusive comments like that is wrong. I will continue to moderate comments, and delete post that are either insulting to other people, or blatantly talk shit about this project.

I'll be happy to try to help if I can get a detailed description of the problem -- without the insults, entitled attitude, and accusatory tone. Post more bile on this thread, and I'll happily delete it.

**Comment by thejameskyle** [comment] 2015-12-05 06:04
As someone who helps maintain a very large open source project I delete nasty comments all the time. I'm not sure what your original comment said @mrchief but you really shouldn't treat contributors poorly. It contributes to burnout, keeps others from wanting to contribute, and all around is a really shitty thing to do.

@mde you have every right to moderate your community. It's not acceptable for people to be treating you poorly and you're doing the right thing. I highly suggest a code of conduct, because it's at least something you can point to when people act shitty.

**Comment by TimothyGu** [comment] 2015-12-05 06:41
Alright there seems to be a lot of traffic going on 'round here. Several points I want to make:

@thejameskyle in the original ticket you wrote <code>`${foo}`</code>. Is it wrapped in a `<%= %>`? Did you declare that variable?

From my GitHub notification email I don't see any out-of-line comment from @mrchief. Maybe he edited the comment after the initial posting, but my personal opinion on these matters is **never delete anything.** (I'm just going onto the general terms now, not on this specific issue) The correct way against such responses is criticizing them, not censoring them. It provides evidence to your argument. If the user deletes the message, it demonstrates shame for their own conduct.

That aside, @mrchief, your test case works totally as expected. I'm not sure what your are trying to achieve by compile JavaScript through EJS, but your `title` variable is not declared, as noted properly by EJS.

For future reference, the "test case" I am talking about here is:

```js
export default () => {
return `
<html>
  <head>
    <title><%= title %></title>
  </head>
  <body>$[body}</body>
</html>`
}
```

this is the version published in the initial comment.

**Comment by thejameskyle** [comment] 2015-12-05 07:01
I've long forgotten what I was working on when this came up, sorry.

> my personal opinion on these matters is never delete anything. (I'm just going onto the general terms now, not on this specific issue) The correct way against such responses is criticizing them, not censoring them. It provides evidence to your argument. If the user deletes the message, it demonstrates shame for their own conduct.

This is a misguided way of thinking when it comes to harassment.

**Comment by mrchief** [comment] 2015-12-05 13:34
@TimothyGu Thanks for bringing back the sample. Its being used in a yeoman generator to generate a boilerplate html. The `title` variable is defined in my actual code but the error will happen even if you remove `<%= title %>` from the sample (and just leave `${body}` in there). 

@thejameskyle Closing the issue without seeking any clarification, especially when the issue is being discussed actively and people are contributing ideas so that people can still use their favorite templating tool, is bit over the line to me. It is like slamming the door on someone's face. Am I overreacting - maybe? But in general, we developers are pretty passionate about things we care about and it hurts when someone treats you in poor light. 

@mde There is no denying of your contribution to the community. I know how I feel about having open issues and I'd like to bring the count lower all the time. Maybe I overreacted to your closing the issue abruptly but I would have gladly edited (even deleted) my comment if you had been open to discussion. Again, thanks for the wonderful templating tool.

**Comment by mde** [comment] 2015-12-05 18:57
Commit fff094f2d80af553f0304c99bdec083ca1af5666 adds an explicit CoC for the project. It's the widely adopted set of principles from http://contributor-covenant.org/.

@mrchief Thank you for the comments. I understand the frustration at the issue being closed. I probably shouldn't have been so quick with the Close button, but the original description of the issue was just "template strings," and they clearly work fine in EJS. I couldn't repro any issue with them whatsoever in my test. This doesn't mean the test was incorrect, this means that the description of the issue is incomplete or incorrect. People open completely invalid issues all the time, and if the issue (as its described) is demonstrably invalid, the normal course of action is to close it. If there's really a valid problem, and it's not being described in a way that maintainers can understand, it's totally reasonable to add some more comments onto the closed thread, or open a new issue and link to it. There wasn't any description of a repro scenario until your angry comment, which I deleted because it was a community party-foul. I probably should have been more patient, and I apologize for that. I did not mean to treat you poorly or make you feel bad.

@TimothyGu I totally get your idea that it's good to have a complete record of the conversation. In theory, that's a good idea. In practice, that's a problem because we're supposed to be having a civil discourse here, and that means removing posts that go outside the bounds of what's acceptable. Removing them means people don't have to read abusive and insulting posts, and also provides motivation for people to keep their communication civil. Unfortunately that also means some context in the conversation might get lost. Everybody has different interpretations of what's acceptable, so opinions can differ about what's over the line. It is admittedly purely a judgement call, and in this scenario, the person making that judgement is me. (Somebody has to.)

Now, with respect to the actual issue here -- I am seeing what @TimothyGu is seeing. I've tried to repro with multiple Nodes (v0.12.9, v4.2.3, v5.1.1), and I am not seeing any problem. Here's what I'm doing.

I have a file, template_str.js, that looks like this (I have corrected for the previous typo):

```javascript
export default () => {
return `
<html>
  <head>
    <title><%= title %></title>
  </head>
  <body>${body}</body>
</html>`
}
```

Then, from the Node REPL, I'm doing this:

```
> var ejs = require('./ejs');
undefined
> var fs = require('fs');
undefined
> var data = fs.readFileSync('./template_str.js').toString();
undefined
> ejs.render(data, {title: 'BAR'});
'export default () => {\nreturn `\n<html>\n  <head>\n    <title>BAR</title>\n  </head>\n  <body>${body}</body>\n</html>`\n}\n'
```

As you can see, the title gets interpolated correctly, leaving the exported arrow function with its returned template string in place.

Now, if this doesn't repro the problem that you see, it doesn't mean the test is "incorrect," it means we're not getting enough info here to see what you're seeing.

**Comment by mrchief** [comment] 2015-12-05 22:32
Is it possible that the most recent version `2.3.4` doesn't have this issue and the version mem-fs-editor uses `2.3.1` has this?

If the versions have nothing to do with it, then I need to dig deeper.

**Comment by mrchief** [comment] 2015-12-05 22:49
Just tested with v2.3.1 and with the node js REPL and the issue doesn't happen. I'll have to dig deeper to see what's causing this issue when used inside a yeoman generator.

If you're inclined to try, here's how to repro my setup:

 - Following the steps to [generate your own generator](http://yeoman.io/authoring/), create a sample generator
 - Following this [example](http://yeoman.io/authoring/file-system.html), add a file with the test sample.
 - Use this code in `index.js` to render the boilerplate html:

```
generators.Base.extend({
  writing: function () {  
    this.fs.copyTpl(
      this.templatePath('template_str.js'),
      this.destinationPath('public/template_str.js'),
      { title: 'Templating with Yeoman' }
    );
  }
});
```
 - `fs.copyTpl` uses `ejs` under the wraps to do the templating. So running the generator: `yo my-generator` will throw the error: `Uncaught ReferenceError: body is not defined`.

Note that it complains about `body` and not `title`.

Maybe its the interplay of things but in theory, if it works in REPL, it should in here too since that's practically what [mem-fs-editor does](https://github.com/SBoudrias/mem-fs-editor/blob/master/actions/copy-tpl.js#L14) as well.

**Comment by RyanZim** [comment] 2016-03-31 13:57
@mrchief: has this been resolved?

**Comment by mrchief** [comment] 2016-04-01 17:01
Haven't been able to get to this. Sorry. You can close this for now. If it happens again I'll ask you to reopen it or create a new one.

**Comment by mde** [comment] 2016-04-01 17:09
Thanks!

**Closed by mde** 2016-04-01 17:09 UTC
Labels: awaiting reply

**Comment by lordjabez** [comment] 2016-07-30 04:44
@mde I believe this is still an issue, see http://stackoverflow.com/questions/37309187/ejs-error-on-es6-template-literals for an example.

**Comment by TimothyGu** [comment] 2016-07-30 05:24
> > This has been a known issue with EJS for some time, possibly related to the underlying mem-fs-editor module
>
> EJS does not depend on any packages, though.

http://stackoverflow.com/questions/37309187/ejs-error-on-es6-template-literals/38625813#comment64721931_38625813

**Comment by RyanZim** [comment] 2016-07-30 14:32
@lordjabez If this is indeed a current issue, please open a _new_ issue, preferably with a reduced test case.

**Comment by lordjabez** [comment] 2016-07-31 18:55
My bad, everyone. The issue I was seeing actually had to do with Yeoman itself, not EJS. Nothing more to see here . . .

**Comment by RyanZim** [comment] 2016-08-01 15:09
Just going to lock this old issue to prevent further posts here.

**Comment by mde** [comment] 2016-08-01 15:22
Thank you!
