### ISSUE TITLE
ejs installation error

### ISSUE THREAD

**Issue by kavya110** [mde/ejs#529] opened 2020-07-03 13:54 UTC
When i try to install ejs in my project, i'm getting the following error.
$ npm i ejs
> ejs@3.1.3 postinstall C:\Users\kavya\Desktop\mini_project\node_modules\ejs
> node --harmony ./postinstall.js

'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN mini_project@1.0.0 No description
npm WARN mini_project@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ejs@3.1.3 postinstall: `node --harmony ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ejs@3.1.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kavya\AppData\Roaming\npm-cache\_logs\2020-07-03T13_54_08_224Z-debug.log

**Comment by RyanZim** [comment] 2020-07-04 18:41
Dupe of https://github.com/mde/ejs/issues/528.

**Closed by RyanZim** 2020-07-04 18:41 UTC
