### ISSUE TITLE
How to cache views when used with Express

### ISSUE THREAD

**Issue by Bluejay47** [mde/ejs#151] opened 2016-04-15 20:45 UTC
I apologize if this is not the correct place for this.

I have EJS set as the default view handler for Express. I am using res.render("template") to render the views, but when I do it this way I don't see any cache files being created.

I have forced caching in the development environment by passing the local variable 'cache' as per the Express documentation. Neither on my server which is in production mode nor in my development environment do I see anything that might be a cached template.

It's completely likely I simply don't understand the process enough to know where to look. Any feedback would be appreciated.

**Comment by RyanZim** [comment] 2016-04-15 22:26
@Bluejay47 If you are rendering a string, you would use: 
```
res.render(str, data, {cache: true, filename: name})
```
where `name` is the name of the template that you want to use as the cache key and `data` is the JS object that you want to be available to the EJS template. (If you don't have any data to pass, you would pass `{}` or `null` instead.)

If you are rendering a file, you should use 
```
res.renderFile(filename, data, {cache: true}, function(err, str){
  // handle errors
  // str -> rendered string
}
```
This way, you don't have to specify the filename manually.

If you have more questions, feel free to ask them! Otherwise, please close this.

**Comment by Bluejay47** [comment] 2016-04-16 02:18
I'll give this a shot. Thanks for your help.

**Comment by Bluejay47** [comment] 2016-04-16 03:28
Out of curiosity, are these instructions for an older version of Express because 'renderFile' doesn't appear to be a valid function in Express 4?

**Comment by RyanZim** [comment] 2016-04-16 11:57
@Bluejay47: what version of EJS are you using? (Check `res.VERSION`) Should be 2.4.1.

**Comment by Bluejay47** [comment] 2016-04-20 21:01
ejs@2.4.1

**Comment by RyanZim** [comment] 2016-04-20 21:04
OK, not sure what the issue is here.

> 'renderFile' doesn't appear to be a valid function in Express 4

What happens when you call `res.renderFile()`?

**Comment by Bluejay47** [comment] 2016-04-20 21:04
Additional notes (just in case they are of interest)

I am requiring ejs in this manner
var ejs = require('ejs'); 

I have both of these set:

app.set('view engine', 'ejs');
app.set('view cache', true);

And I am using the Express response object to render files in the follow manner:

res.render(fileName, {"cache": true, "data" : data});

**Comment by Bluejay47** [comment] 2016-04-20 21:07
This is what I am seeing in my error log when I try to use res.renderFile

error: [TypeError: res.renderFile is not a function] stack=TypeError: res.renderFile is not a function
    at d:\Projects\Estimake\views.js:119:14
    at Layer.handle [as handle_request] (d:\Projects\Estimake\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\Projects\Estimake\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\Projects\Estimake\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\Projects\Estimake\node_modules\express\lib\router\layer.js:95:5)
    at d:\Projects\Estimake\node_modules\express\lib\router\index.js:277:22

**Comment by RyanZim** [comment] 2016-04-20 21:14
Sorry, I'm not real familiar with Express. The instructions I gave you were incorrect.

Express uses the `__express()` method, which is an alias of `ejs.renderFile()`. `res.render(fileName, {"cache": true, "data" : data}); ` should work correctly.

**Comment by RyanZim** [comment] 2016-04-20 21:35
You said:

> Neither on my server which is in production mode nor in my development environment do I see anything that might be a cached template.

No wonder you can't find them:

> If [cache is] enabled, express stores compiled template in process memory and renders the cached version. This way no temporary cache files are generated and the template is retrieved quickly from memory.

Source: http://stackoverflow.com/questions/25858431/when-using-express-with-nodejs-how-does-view-cache-work

---

Sorry for all the misinformation; EJS itself also has a caching mechanism (https://github.com/mde/ejs#caching) and I thought you were referring to that.

I never used express in production, so I don't understand it very well. All in all, it's been a learning experience for both of us.

I'm closing since this should (hopefully) answer your question. Feel free to reopen if I missed something.

**Closed by RyanZim** 2016-04-20 21:35 UTC
Labels: question

**Comment by spddl** [comment] 2016-04-20 23:28
Sorry but I had the same problem that's my solution:

```
var express = require('express'),
    // or with minify: // minify = require('html-minifier').minify,
    ejs = require('ejs');

    var app = express()
    .get('/:id?', function(req, res){
      //console.log('ejs.VERSION '+ejs.VERSION); // ejs.VERSION 2.4.1
      
      ejs.renderFile('./views/index.ejs',{ data: data}, function(err, html){
        err && console.error(err); res.send(html)
        // or with minify: // err && console.error(err); res.send(minify(html, { collapseWhitespace: true, quoteCharacter: true, removeAttributeQuotes: true, minifyJS: true }));
      })
      
    }.listen(80);
```

**Comment by RyanZim** [comment] 2016-04-20 23:45
@spddl That would be another way to do it. That method would use EJS's cache instead of express'.

**Comment by Bluejay47** [comment] 2016-04-22 03:33
Thanks for all of the info. I really appreciate the feedback and hope I didn't go too off topic for the forum.
