### ISSUE TITLE
Not able to access array of object of array of object and so on in ejs with script

### ISSUE THREAD

**Issue by tirathsharma098** [mde/ejs#662] opened 2022-04-10 12:05 UTC
here ``` countryData ``` is an array of object of object. ``` [ {name: 'countryname' , states : [{name : 'stateName'}, .............]}, .......... ] ```
I am trying to append all states name for respective selected country when user select an country and taking the sending the countryData while rendering to template.
But, I am not able to use variable name that i got while rendering interchangebly which is necessary.
My ejs script file,
![image](https://user-images.githubusercontent.com/70467735/162616663-39df4529-6912-425c-a8e3-e238ff7f39a3.png)
partial include
![image](https://user-images.githubusercontent.com/70467735/162616982-c0c51e81-cfbc-4e08-b594-20748f33d9c1.png)
select Input
![image](https://user-images.githubusercontent.com/70467735/162617015-4f3ded7c-e2f8-49bf-8679-53982b1ff043.png)
I am able to append country name successfully query is just for states name.
Because not able to access array of object of array of object and so on in ejs with script.

**Comment by mde** [comment] 2022-04-10 16:47
It would appear that part of the problem is that you're mixing client- and server-side execution with your EJS. I can't tell from your first code example if you're trying to create client-side-executable JavaScript with your server-rendering, or build a client-renderable template with your client-side execution (or if you're just mixing things together, and hoping for the best).

I am going to close this issue because it is almost certainly not a problem with the EJS library itself. And you don't provide a minimal (EJS-only) failing example, there's very little I can do to help. This is a problem in your application code somewhere. If you can give me that minimal, EJS-only example, feel free to reopen.

**Closed by mde** 2022-04-10 16:47 UTC
