### ISSUE TITLE
Module adds a global "fn"

### ISSUE THREAD

**Issue by dougwilson** [mde/ejs#3] opened 2015-01-04 21:38 UTC
Regression from commit f314d88a5c5ae6b3474293b789129b2334e933c9 causes `fn` property to be added to the global object.

**Comment by mde** [comment] 2015-01-04 23:20
Fixed in d428a2fc21ef5bdb6ffeabaf5caefd293c00d4aa, pushed to NPM, v2.0.5.

**Closed by mde** 2015-01-04 23:20 UTC

**Comment by dougwilson** [comment] 2015-01-04 23:22
Thanks!

**Comment by mde** [comment] 2015-01-04 23:28
No, thank you. Much appreciated!

**Comment by knownasilya** [comment] 2016-10-14 02:50
Seeing this again with 2.5.2

**Comment by RyanZim** [comment] 2016-10-14 13:47
@knownasilya Thanks for reporting! Please open a new issue with a reduced test case so we can investigate this.

Locking since this is an old issue.

**Comment by mde** [comment] 2016-10-17 20:04
Incidentally I can't repro this regression with v2.5.2 -- not with CommonJS in Node, not with the built file in the browser.
