### ISSUE TITLE
CSS not present in some .ejs files

### ISSUE THREAD

**Issue by aya1337** [mde/ejs#538] opened 2020-08-15 08:49 UTC
EJS is not rendering some pages right in certain paths. Even if i duplicate an already working page and use it for the path, the css doesn't appear

The main css is required in the header partials (partials/header)

and this is what I'm doing
```html
<head>
    <%- include('partials/header') %>
</head>
```
the header shows up without any CSS
and in other files, it shows up just fine

**Comment by mde** [comment] 2020-08-20 16:06
Looks like you're using the correct opening tag for unescaped output. I would need a lot more information to even begin guessing what the issue is, but given how well-tested EJS is, it is almost certainly not an issue with EJS itself. If you really believe it's a problem with EJS, ideally you would provide me a minimal failing example that uses *only* EJS, with input and output that demonstrates the problem.

Given all of that, I am going to close this issue. Please feel free to reopen if you can provide that minimal failing example.

**Closed by mde** 2020-08-20 16:06 UTC
