### ISSUE TITLE
Is it possible to get the line number in the ejs errors?

### ISSUE THREAD

**Issue by IonicaBizau** [mde/ejs#119] opened 2015-11-04 18:03 UTC
<sub>I originally posted [this question on StackOverflow](http://stackoverflow.com/q/33409176/1420197). This is the original post:</sub>

(Suppose) I have a *huge* ejs file containing JavaScript snippets. When I compile it, I get the following error:

> `SyntaxError: Unexpected token ) in mytemplate.ejs while compiling ejs`

While it's obvious there is a syntax error in my template, I can't know where the error is.

I have full access to the error object so, I was thinking if somewhere the error contains the line with the problem (in a similar way like the JavaScript engines tell you that there is a problem on a specific line).

I tried to access the `err.stack` field, but it only shows me the error origin (which comes from the ejs library), so that's not really helpful.

Is there a way to know where the syntax error is in the ejs file?

I'm using the [`ejs`](https://github.com/mde/ejs) package.

**Comment by jmcollin78** [comment] 2015-11-04 19:50
Same problem for me: https://github.com/mde/ejs/issues/118
I try the compileDebug and debug=true options without success.
The only thing I found is to update the code of module to console.log the curent line....

JM.

**Comment by IonicaBizau** [comment] 2015-11-04 19:51
> The only thing I found is to update the code of module to console.log the curent line....

Oh, can you give me the exact link? Thanks!!

**Comment by jmcollin78** [comment] 2015-11-04 19:55
For my case it was at line 500 of the ejs.js file. The generateSource function.
Add a console.log('Current line : "%s"', line) at line 515 and you will see where the problem is.

**Comment by mde** [comment] 2015-11-23 22:19
Would love a PR that implements this for everybody. :)

**Comment by dgofman** [comment] 2015-12-02 07:17
I am providing temporary solution its better than nothing

https://github.com/tj/ejs/issues/212

Update node_modules\ejs\lib\ejs.js 
Line 505

generateSource: function () {
    var self = this
      , matches = this.parseTemplateText()
      , d = this.opts.delimiter;

    if (matches && matches.length) {
    this.source = '    ; __filename = "' + this.opts.filename.replace(/\\/g,  '/') + '"\n';

**Comment by dgofman** [comment] 2016-01-29 02:10
Guys, please can you fix in the next release I am always loosing these changes after NPM install

**Comment by mde** [comment] 2016-01-29 07:24
Give us a PR with your workaround, and I'll be happy to merge it. This is how open source works, folks.

**Comment by dgofman** [comment] 2016-02-01 06:23
Before I provided only a workaround how can I detect a file. Now I providing complete Fix for this issue

https://github.com/mde/ejs/pull/129

**Comment by dgofman** [comment] 2016-02-02 16:41
Please can someone merge PR 129

**Comment by dgofman** [comment] 2016-02-02 16:44
Please can you merge https://github.com/mde/ejs/pull/129

Thanks,
David

On Thu, Jan 28, 2016 at 11:24 PM, Matthew Eernisse <notifications@github.com

**Comment by mde** [comment] 2016-02-02 22:53
Very underwater with work. I'll definitely get to in the next day or so. Thanks for your patience!

**Comment by dgofman** [comment] 2016-02-06 21:30
Did you get a time to look my changes?

**Comment by IonicaBizau** [comment] 2016-02-07 06:54
@dgofman Nice work, but my issue is saying that when having unexpected error we don't get the line number.

For example, put this in `body.html`:

```html
<p><%= var %></p>
```

Then in the browser we get:

```
SyntaxError: Unexpected token var in /home/ionicabizau/Documents/ejs/sample/index.html while compiling ejs
   at Function (native)
   at Object.Template.compile (/home/ionicabizau/Documents/ejs/lib/ejs.js:485:12)
   at Object.compile (/home/ionicabizau/Documents/ejs/lib/ejs.js:289:16)
   at handleCache (/home/ionicabizau/Documents/ejs/lib/ejs.js:148:16)
   at View.exports.renderFile [as engine] (/home/ionicabizau/Documents/ejs/lib/ejs.js:358:14)
   at View.render (/home/ionicabizau/Documents/ejs/node_modules/express/lib/view.js:126:8)
   at tryRender (/home/ionicabizau/Documents/ejs/node_modules/express/lib/application.js:639:10)
   at EventEmitter.render (/home/ionicabizau/Documents/ejs/node_modules/express/lib/application.js:591:3)
   at ServerResponse.render (/home/ionicabizau/Documents/ejs/node_modules/express/lib/response.js:961:7)
   at /home/ionicabizau/Documents/ejs/sample/index.js:7:6
```

So, we don't get the line number.
But I think it can be improved. :+1:

**Comment by ciroreed** [comment] 2016-02-08 21:44
An easy trick to know where ejs template broke. 

enable pause exceptions on chrome debugger (F12, script tab). 

U will see that it stops processing here: 

```javascript
try {
      fn = new Function(opts.localsName + ', escape, include, rethrow', src);
    }
    catch(e) {
      // istanbul ignore else
      if (e instanceof SyntaxError) {
        if (opts.filename) {
          e.message += ' in ' + opts.filename;
        }
        e.message += ' while compiling ejs';
      }
      throw e;
    }```

evaluate in console the "src" val. Then u will see the trace. Now you can click in the instance of the console VMXXX:58 <--- click here

**Comment by dgofman** [comment] 2016-02-08 23:42
@ciroreed You solution shouldn't work. @IonicaBizau I fixed issue in code related in template. But your in compilation error (Syntax Error) handling outside template try/catch block. When I will get a time I will deep look how to fix it. Currently I don't have experiences writing invalid JavaScript code :)

**Comment by IonicaBizau** [comment] 2016-02-09 04:35
> Currently I don't have experiences writing invalid JavaScript code :)

I have a lot. :grin: These syntax errors appear when quickly writing something and obviously missing something.

I am not familiar with the ejs library code, but I think there should be an error/exception that has the `stack` property and that will maybe output something useful. Not sure. :thought_balloon:

**Comment by TimothyGu** [comment] 2016-02-09 05:10
> but I think there should be an error/exception that has the stack property and that will maybe output something useful.

V8 is [notorious](https://bugs.chromium.org/p/v8/issues/detail?id=2589) for not adding line numbers to syntax errors, so there's nothing we can do. In Jade/Pug we simply used Acorn (a JavaScript parser) to parse the code. This is of course not possible in EJS since we are trying to keep the code size down to a bare minimum.

**Comment by ciroreed** [comment] 2016-02-09 08:13
@dgofman my solution works because i can see line errror as i told you. Not in production environment, just for debugging

**Comment by RyanZim** [comment] 2016-03-25 14:57
@dgofman: i am looking into it.

**Comment by RyanZim** [comment] 2016-04-18 19:16
@IonicaBizau PR #129 was merged. Can we close this or is there something else that needs resolved?

**Comment by dgofman** [comment] 2016-04-18 19:57
I cannot get latest version you didn't change in package.json new version
and pushed to NPM

https://www.npmjs.com/package/ejs


   - [image: mde] mde  <https://www.npmjs.com/~mde>published 3 months ago
   - *2.4.1* is the latest of 48 releases

**Comment by IonicaBizau** [comment] 2016-04-19 03:41
@RyanZim Probably that's a nice improvement, but still my issue is not fixed:

```ejs
<h1>Users</h1>

<% foo( %>
<% //    ^ Yes, that's supposed to be there to demonstrate the error %>
<% function user(user) { %>
  <li><strong><%= user.name %></strong> is a <%= user.age %> year old <%= user.species %>.</li>
<% } %>

<ul>
  <% users.map(user) %>
</ul>
```

By compiling this, I get:

```js
$ node functions.js 
/home/ionicabizau/ejs/lib/ejs.js:495
      throw e;
      ^

SyntaxError: Unexpected token ; in /home/ionicabizau/ejs/examples/functions.ejs while compiling ejs
    at Function (native)
    at Object.Template.compile (/home/ionicabizau/ejs/lib/ejs.js:485:12)
    ...
```

So, for a big ejs template, and such a small mistake (a missint closing `)`), it's very hard to debug the things. I expect to see the line number where this is crashing.

**Comment by RyanZim** [comment] 2016-04-19 12:06
@IonicaBizau It's a pain, but I don't know of much we can do. Node doesn't output line numbers when parsing JS via `new Function`, which is what we're doing. Here's the code:
```
    try {
      fn = new Function(opts.localsName + ', escape, include, rethrow', src);
    }
    catch(e) {
      // istanbul ignore else
      if (e instanceof SyntaxError) {
        if (opts.filename) {
          e.message += ' in ' + opts.filename;
        }
        e.message += ' while compiling ejs';
      }
      throw e;
    }
```
(See it at https://github.com/mde/ejs/blob/master/lib/ejs.js#L484-L496)

There is a bug filed for node's underlying V8 parser: https://bugs.chromium.org/p/v8/issues/detail?id=2589. It doesn't seem that this is high priority to the V8 team though. :frowning:

**Comment by IonicaBizau** [comment] 2016-04-19 14:20
> Node doesn't output line numbers when parsing JS via new Function, which is what we're doing.

@RyanZim True. I did take a quick look at the code and my question is why do you do it this way? We have the `vm` module which seems to output fancy errors:

```js
> require("vm").runInThisContext("x = 42;")
42
> require("vm").runInThisContext("x = ;")
evalmachine.<anonymous>:1
x = ;
    ^
SyntaxError: Unexpected token ;
    at Object.exports.runInThisContext (vm.js:53:16)
    at repl:1:15
    at REPLServer.defaultEval (repl.js:260:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:429:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
> require("vm").runInThisContext("foo(")
evalmachine.<anonymous>:1
foo(
   ^
SyntaxError: Unexpected end of input
    at Object.exports.runInThisContext (vm.js:53:16)
    at repl:1:15
    at REPLServer.defaultEval (repl.js:260:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:429:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
```

Maybe using `vm` would be a solution.

**Comment by RyanZim** [comment] 2016-04-19 14:52
> why do you do it this way?

I don't know, perhaps @mde or @TimothyGu does. As far as the `vm` module, If you can figure out a way to do it, I would welcome a PR.

**Comment by IonicaBizau** [comment] 2016-04-19 15:05
@RyanZim On the other side I'm pretty sure it will not work in the same way in the browser unless `browserify` or so really has a nice solution for the `vm`.

**Comment by RyanZim** [comment] 2016-04-19 15:12
@IonicaBizau Yeah, hadn't thought of that. Here's browserify's `vm` module: https://github.com/substack/vm-browserify. Pretty sparse. And I'm still not sure `vm` will help much.

**Comment by RyanZim** [comment] 2016-05-11 21:47
@IonicaBizau: I gave up on getting node to output good errors and wrote an EJS Linter/Syntax Checker instead!

https://github.com/RyanZim/EJS-Lint

It's not finished, but it's a step in the right direction. It uses acorn under the hood to give good error messages with the line number included.

In the example you gave [https://github.com/mde/ejs/issues/119#issuecomment-211714702], it would say that the error is at line 10, since that is the first piece of JS after the error. Not perfect, but better than no line number.

CC: @mde @TimothyGu

**Comment by IonicaBizau** [comment] 2016-05-12 02:59
@RyanZim That sounds good! :+1:

**Comment by zen-mde** [comment] 2016-05-24 17:37
Fixed by https://github.com/mde/ejs/pull/129

**Comment by mde** [comment] 2016-05-24 17:42
Fixed by https://github.com/mde/ejs/pull/129

**Closed by mde** 2016-05-24 17:42 UTC

**Comment by IonicaBizau** [comment] 2016-05-24 18:11
@mde Was this really fixed? That pull request is related but it does *not* fix the issue, from what I know.

**Comment by RyanZim** [comment] 2016-05-24 18:16
@IonicaBizau 

> That pull request is related but it does not fix the issue, from what I know.

You are correct. I don't think this is something we can fix in the ejs core; that's why I created EJS-Lint.

I was thinking that sometime in the future I might make ejs `console.log()` a message like:

> If the above error is not helpful, you may want to try ejs-lint

when it logs a js syntax error. (Of course, that's if @mde is OK with that)

Right now, EJS-Lint isn't fully featured enough.

**Comment by IonicaBizau** [comment] 2016-05-24 18:22
@RyanZim Ah, indeed! :+1: Maybe the error message should be updated with something like *use `ejs-lint` to find the source of error*––or so. :grin: Nice work!

**Comment by mde** [comment] 2016-05-24 18:23
Happy to reopen, if it's something we can really fix -- @RyanZim, should this be reopened?

**Comment by RyanZim** [comment] 2016-05-24 18:28
@mde Nope, I'll open a new issue when EJS-Lint is mature enough. Meanwhile PR's are welcome at https://github.com/RyanZim/EJS-Lint. :wink:

**Comment by Meignanam** [comment] 2020-07-15 15:30
guys, could you help me , which kind of error , i am getting lag perticular issue



SyntaxError: Unexpected token '/' in E:\PASSPORT\views\register.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (E:\PASSPORT\node_modules\ejs\lib\ejs.js:661:12)
    at Object.compile (E:\PASSPORT\node_modules\ejs\lib\ejs.js:396:16)
    at handleCache (E:\PASSPORT\node_modules\ejs\lib\ejs.js:233:18)
    at tryHandleCache (E:\PASSPORT\node_modules\ejs\lib\ejs.js:272:16)
    at View.exports.renderFile [as engine] (E:\PASSPORT\node_modules\ejs\lib\ejs.js:489:10)
    at View.render (E:\PASSPORT\node_modules\express\lib\view.js:135:8)
    at tryRender (E:\PASSPORT\node_modules\express\lib\application.js:640:10)
    at Function.render (E:\PASSPORT\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (E:\PASSPORT\node_modules\express\lib\response.js:1012:7)
