### ISSUE TITLE
High CVE for latest version of  ejs@3.1.9

### ISSUE THREAD

**Issue by sonu-jmh** [mde/ejs#727] opened 2023-05-10 17:48 UTC
There is a high severity CVE reported by Mend(Whitesource) ejs@3.1.9. NPM showing 3.1.9 as the latest available version. Is there any update when the fix is planned to be released?

**Comment by RyanZim** [comment] 2023-05-10 18:08
Duplicate of https://github.com/mde/ejs/issues/720#issuecomment-1540435858

**Closed by RyanZim** 2023-05-10 18:08 UTC
