### ISSUE TITLE
adding underscore no longer works

### ISSUE THREAD

**Issue by artofspeed** [mde/ejs#131] opened 2016-03-03 17:44 UTC
In **ejs v1**, I could do

```
var _ = require('underscore')
app.locals._ = _;
```

Then underscore would be available in ejs template. However after I moved to **ejs v2**, it keeps saying `_ is not defined`. Why?

**Comment by mde** [comment] 2016-03-04 06:10
I am assuming you're talking about an Express app with EJS. I cannot reproduce this problem with Express v4.13.4, EJS v2.4.1, and Underscore v1.8.3.

I do `app.locals._ = require('underscore');` and my template looks like this:

```javascript
<%= typeof locals._.each %>
```
The page renders the word "function."

**Comment by RyanZim** [comment] 2016-03-24 14:04
@artofspeed, can you explain how to reproduce this?

**Comment by RyanZim** [comment] 2016-03-31 14:23
@artofspeed, I'm giving you 7 more days to respond or I will close this.

**Comment by RyanZim** [comment] 2016-04-07 13:24
No Response; Closing.

**Closed by RyanZim** 2016-04-07 13:24 UTC
Labels: awaiting reply
