### ISSUE TITLE
EJS Template Problem

### ISSUE THREAD

**Issue by demonicpagan** [mde/ejs#199] opened 2016-09-02 20:19 UTC
I created the following gist (https://gist.github.com/demonicpagan/0f35a88d9571bf5ada460b7c9e042d93) with the files that would be of assistance, but I cannot figure out where I am going wrong to where my output ends up like the following:

![2016-09-02_14-55-17](https://cloud.githubusercontent.com/assets/92093/18217110/fe44ff4a-7128-11e6-96cc-9f958ee43ddd.png)

**Comment by RyanZim** [comment] 2016-09-02 21:36
Your EJS files look fine. My guess is that your mis-configuring express. I'm pretty well express-illiterate, so can't help you with that. @TimothyGu or @mde could help you better.

**Comment by demonicpagan** [comment] 2016-09-04 05:13
That would be fantastic if either one could give me some insight.

**Comment by demonicpagan** [comment] 2016-09-06 18:35
Any chance that someone has been able to look into this?

**Comment by RyanZim** [comment] 2016-09-07 12:57
@demonicpagan: @TimothyGu must be extra busy right now. Have you tried posting this on stackoverflow.com?

**Comment by demonicpagan** [comment] 2016-09-07 13:40
I have not. I don't think I have the rep to post anything there.

**Comment by mde** [comment] 2016-09-07 13:53
I'll take a look today. Sorry for the delay.

**Comment by mde** [comment] 2016-09-07 14:25
Hard to tell because your example is mixing both Express and Angular code, but it looks like you're not actually processing the template with EJS -- it looks like you're using Handlebars or something else. Your `{{fileViewer}}` variable is getting interpolated, rendering as "Please select a file to view its contents," and then the raw EJS source code is getting spit out. Note that the double-curly brackets are not EJS code -- they're Mustache/Handlebars.

I'm happy to help debug actual problems with EJS, but generally what needs to happen there is (1) make sure it's a problem with the library in question, and (2) reduce the problem down to the minimal possible example that reproduces the problem. (These two things kind of go hand-in-hand.)

In your case, it seems like you have a larger problem with the Web framework your using (Express) -- you'd probably have more luck addressing your problem by asking experienced Express users in whatever community channels exist: https://expressjs.com/en/resources/community.html

**Comment by demonicpagan** [comment] 2016-09-07 15:47
I thought that EJS was being used since in my app.js folder I have the following set: 

`   app.engine('html', require('ejs').renderFile);
    app.set('view engine', 'html');`

**Comment by mde** [comment] 2016-09-07 16:03
The EJS tags are doing nothing, and the HBS variables are being interpolated. It's apparently not actually using EJS. Maybe those are not being treated as HBS -- does Jade use the same double-curlies? Maybe it's just using the default of Jade.

Not sure why you're not just doing `app.set('view engine', 'ejs');` -- I'm not familiar with `app.engine`.

In any case, this does not in any way appear to be a problem with EJS.

**Comment by RyanZim** [comment] 2016-10-14 14:03
> this does not in any way appear to be a problem with EJS.

Agreed, closing.

**Closed by RyanZim** 2016-10-14 14:03 UTC
Labels: question
